[package]
name = "courseplanner"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.23.1"

