// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.

// Generated by Quartus Prime Version 20.1.1 Build 720 11/11/2020 SJ Standard Edition
// Created on Tue Apr 14 16:38:43 2026

// synthesis message_off 10175

`timescale 1ns/1ns

module Lab11FSM (
    reset,clock,transition,
    hexout[3:0]);

    input reset;
    input clock;
    input transition;
    tri0 reset;
    tri0 transition;
    output [3:0] hexout;
    reg [3:0] hexout;
    reg [3:0] reg_hexout;
    reg [4:0] fstate;
    reg [4:0] reg_fstate;
    parameter A=0,C=1,E=2,D=3,B=4;

    initial
    begin
        reg_hexout <= 4'b0000;
    end

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset or transition or reg_hexout)
    begin
        if (reset) begin
            reg_fstate <= A;
            reg_hexout <= 4'b0000;
            hexout <= 4'b0000;
        end
        else begin
            reg_hexout <= 4'b0000;
            hexout <= 4'b0000;
            case (fstate)
                A: begin
                    if ((transition == 1'b1))
                        reg_fstate <= D;
                    else if ((transition == 1'b0))
                        reg_fstate <= B;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= A;

                    reg_hexout <= 4'b0001;
                end
                C: begin
                    if ((transition == 1'b0))
                        reg_fstate <= C;
                    else if ((transition == 1'b1))
                        reg_fstate <= D;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= C;

                    reg_hexout <= 4'b0011;
                end
                E: begin
                    if ((transition == 1'b1))
                        reg_fstate <= E;
                    else if ((transition == 1'b0))
                        reg_fstate <= B;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= E;

                    reg_hexout <= 4'b0101;
                end
                D: begin
                    if ((transition == 1'b1))
                        reg_fstate <= E;
                    else if ((transition == 1'b0))
                        reg_fstate <= B;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= D;

                    reg_hexout <= 4'b0100;
                end
                B: begin
                    if ((transition == 1'b0))
                        reg_fstate <= C;
                    else if ((transition == 1'b1))
                        reg_fstate <= D;
                    // Inserting 'else' block to prevent latch inference
                    else
                        reg_fstate <= B;

                    reg_hexout <= 4'b0010;
                end
                default: begin
                    reg_hexout <= 4'bxxxx;
                    $display ("Reach undefined state");
                end
            endcase
            hexout <= reg_hexout;
        end
    end
endmodule // Lab11
