cpu = ["Model", "Bits", "Cores", "Clock Rate"]
ram = ["Size (GB)", "Number of Sticks", "DDR"]
gpu = ["Model", "Memory Size (GB)", "GDDR", "Memory Speed (GBPS)", "Clock Speed (MHz)"]
harddrive = ["Size (GB)", "RPM", "Speed (Gb/s)", "SSD or HDD"]
refcpu = ["Best CPU ever", 64, 8, 4]
refram = [16, 4, 3000, 4]
refgpu = ["GTX 980", 5, 4, 4.6, 1126]
refharddrive = [1000, 7200, 6, "SSD"]
ref = [refcpu, refram, refgpu, refharddrive]
percentcpu = 0.25
percentram = 0.25
percentgpu = 0.25
percentharddrive = 0.25
percents = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
totals = [0, 0, 0, 0]
cpu[0] = input("What model is your CPU?")
cpu[1] = float(input("How Many Bits Is it? (32/64)"))
percents[0] = cpu[1]/refcpu[1]
cpu[2] = int(input("How many cores does it have"))
percents[1] = cpu[2]/refcpu[2]
cpu[3] = float(input("What is its Clock Rate?"))
percents[2] = cpu[3]/refcpu[3]
ram[0] = float(input("How much RAM do you have?"))
percents[3] = ram[0]/refram[0]
ram[1] = int(input("How many sticks of RAM do you have?"))
percents[4] = ram[1]/refram[1]
ram[2] = int(input("How much DDR is that RAM?"))
percents[5] = ram[2]/refram[2]
gpu[0] = input("What Model is your GPU?")
gpu[1] = float(input("How Much Memory does Your GPU have?"))
percents[6] = gpu[1]/refgpu[1]
gpu[2] = int(input("What GDDR level is the memory?"))
percents[7] = gpu[2]/refgpu[2]
gpu[3] = float(input("How fast is your GPU's Memory? (Gb/s)"))
percents[8] = gpu[3]/refgpu[3]
gpu[4] = float(input("How fast is your GPU's clock? (MHz)"))
percents[9] = gpu[4]/refgpu[4]
harddrive[0] = float(input("How big is your hard drive?"))
percents[10] = harddrive[0]/refharddrive[0]
harddrive[1] = int(input("How fast does your hard drive spin? (RPM)"))
percents[11] = harddrive[1]/refharddrive[1]
harddrive[2] = float(input("How fast is your hard drive? (Gb/s)"))
percents[12] = harddrive[2]/refharddrive[2]
harddrive[3] = input("Is your hard drive an SSD or HDD?")
