from time import sleep
import pygame
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
PINK = (255, 0, 255)
BLUE = (0, 0, 255)
ORANGE = (255, 100, 0)
PURPLE = (100, 0, 100)
size = [700, 500]
screen = pygame.display.set_mode(size)
pygame.init()
pygame.display.set_caption("This is the color red.")
screen.fill(RED)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color orange.")
screen.fill(ORANGE)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color yellow.")
screen.fill(YELLOW)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color green.")
screen.fill(GREEN)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color blue.")
screen.fill(BLUE)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color purple.")
screen.fill(PURPLE)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color black.")
screen.fill(BLACK)
pygame.display.flip()
sleep(1.5)
pygame.display.set_caption("This is the color white.")
screen.fill(WHITE)
pygame.display.flip()
sleep(2)
pygame.display.quit()
pygame.quit()
exit()
